apiVersion: v1
<<<<<<< Updated upstream
appVersion: "1.77.0"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.77.0
=======
appVersion: "1.78.0"
description: A Helm chart that sets up Kubecost, Prometheus, and Grafana to monitor
  cloud costs.
name: cost-analyzer
version: 1.78.0
>>>>>>> Stashed changes
annotations:
  "artifacthub.io/links": |
    - name: Homepage
      url: https://www.kubecost.com
